services:
  - type: web
    name: chambafacil
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
    healthCheckPath: /health
